spring:
  application:
    name: daily-history-server

  cache:
    cache-names: dailyContentByDate
    caffeine:
      spec: maximumSize=20,expireAfterWrite=24h

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true

server:
  port: ${PORT:8080}
  jwtSecret: ${SERVER_JWTSECRET}
  jwtExpirationMs: ${SERVER_JWTEXPIRATIONMS:86400000}
  pipelineSecret: ${PIPELINE_SECRET}

google:
  oauth:
    client-ids: ${GOOGLE_OAUTH_CLIENT_IDS}

cloudinary:
  cloudName: ${CLOUDINARY_CLOUD_NAME}
  apiKey: ${CLOUDINARY_API_KEY}
  apiSecret: ${CLOUDINARY_API_SECRET}
  folder: ${CLOUDINARY_FOLDER:daily-history}
